# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8906aeaeb3b830b1f2975df78648cbcceac58477521a010361379de3bcf28f9ab34384a4ca756fc628f376829cf2cfb55fafc56b87698c8475a167ace6e0b3aa

test:
  secret_key_base: a6825400e4adfc94b9f348fd44a0f9eda28951cdbd12cb9c89ca1bb62fad7006ef95720c19104a614a6a5a998d69b76599ed02b7e54a4e5b27ae6768a834aec7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
